### ISSUE TITLE
关于知乎文章8.小程序与Token中GET User Data部分小程序报错401 (Unauthorized)的问题

### ISSUE THREAD

**Issue by blzckcxt** [stacklens/django-weixinapp-tutorial#1]
VM9 asdebug.js:10 GET http://127.0.0.1:8000/api/weixin/data/ 401 (Unauthorized)
(env: Windows,mp,1.06.2208010; lib: 2.19.4)

{data: {…}, header: {…}, statusCode: 401, cookies: Array(0), errMsg: "request:ok"}
cookies: []
data:
code: "token_not_valid"
detail: "Given token not valid for any token type"
messages: Array(1)
0: {token_class: "AccessToken", token_type: "access", message: "Token is invalid or expired"}
length: 1
nv_length: (...)
__proto__: Array(0)
__proto__: Object
errMsg: "request:ok"
header: {Date: "Thu, 11 Aug 2022 06:58:05 GMT", Server: "WSGIServer/0.2 CPython/3.10.4", Content-Type: "application/json", WWW-Authenticate: "Bearer realm="api"", Vary: "Accept", …}
statusCode: 401
__proto__: Object

请问如何解决此问题？

**Comment by blzckcxt** [comment]
已解决此问题。

**Comment by stacklens** [comment]
> 已解决此问题。

报错说的是 token 无效。最后是如何解决的呢？
